import { AbilityIdSchema, PhaseIdSchema, RoleIdSchema } from '@agentwolf/contracts'
import type { PhaseGraph, PhaseNode } from './types.js'

function phase(value: string): ReturnType<typeof PhaseIdSchema.parse> {
  return PhaseIdSchema.parse(value)
}

const nodes: PhaseNode[] = [
  {
    id: phase('phase-night-guard'),
    labelKey: 'phases.nightGuard',
    mode: 'parallel',
    actionType: 'night-action',
    abilityId: AbilityIdSchema.parse('ability-guard-protect'),
    actorSelector: `role:${RoleIdSchema.parse('role-guard')}`,
    activeWhen: `role-alive:${RoleIdSchema.parse('role-guard')}`,
    edges: [{ to: phase('phase-night-wolf-council') }],
  },
  {
    id: phase('phase-night-wolf-council'),
    labelKey: 'phases.nightWolfCouncil',
    mode: 'sequential',
    actionType: 'speech',
    actorSelector: 'faction-alive:werewolf',
    edges: [{ to: phase('phase-night-wolf-vote') }],
  },
  {
    id: phase('phase-night-wolf-vote'),
    labelKey: 'phases.nightWolfVote',
    mode: 'parallel',
    actionType: 'vote',
    abilityId: AbilityIdSchema.parse('ability-werewolf-kill'),
    actorSelector: 'faction-alive:werewolf',
    edges: [{ to: phase('phase-night-witch') }],
  },
  {
    id: phase('phase-night-witch'),
    labelKey: 'phases.nightWitch',
    mode: 'parallel',
    actionType: 'night-action',
    actorSelector: `role:${RoleIdSchema.parse('role-witch')}`,
    activeWhen: `role-alive:${RoleIdSchema.parse('role-witch')}`,
    edges: [{ to: phase('phase-night-seer') }],
  },
  {
    id: phase('phase-night-seer'),
    labelKey: 'phases.nightSeer',
    mode: 'parallel',
    actionType: 'night-action',
    abilityId: AbilityIdSchema.parse('ability-seer-inspect'),
    actorSelector: `role:${RoleIdSchema.parse('role-seer')}`,
    activeWhen: `role-alive:${RoleIdSchema.parse('role-seer')}`,
    edges: [{ to: phase('phase-night-resolve') }],
  },
  {
    id: phase('phase-night-resolve'),
    labelKey: 'phases.nightResolve',
    mode: 'automatic',
    edges: [
      { to: phase('phase-day-announcement'), when: 'has-winner' },
      { to: phase('phase-sheriff-signup'), when: 'first-day-with-sheriff' },
      { to: phase('phase-day-announcement') },
    ],
  },
  {
    id: phase('phase-sheriff-signup'),
    labelKey: 'phases.sheriffSignup',
    mode: 'parallel',
    actionType: 'sheriff-action',
    actorSelector: 'publicly-alive',
    edges: [
      { to: phase('phase-sheriff-speech'), when: 'multiple-standing-candidates' },
      { to: phase('phase-sheriff-resolve') },
    ],
  },
  {
    id: phase('phase-sheriff-speech'),
    labelKey: 'phases.sheriffSpeech',
    mode: 'sequential',
    actionType: 'speech',
    actorSelector: 'standing-sheriff-candidates',
    edges: [{ to: phase('phase-sheriff-withdraw') }],
  },
  {
    id: phase('phase-sheriff-withdraw'),
    labelKey: 'phases.sheriffWithdraw',
    mode: 'parallel',
    actionType: 'sheriff-action',
    actorSelector: 'standing-sheriff-candidates',
    edges: [
      { to: phase('phase-sheriff-vote'), when: 'multiple-standing-candidates' },
      { to: phase('phase-sheriff-resolve') },
    ],
  },
  {
    id: phase('phase-sheriff-vote'),
    labelKey: 'phases.sheriffVote',
    mode: 'parallel',
    actionType: 'vote',
    actorSelector: 'original-sheriff-noncandidates',
    edges: [
      { to: phase('phase-sheriff-runoff-speech'), when: 'sheriff-vote-tied' },
      { to: phase('phase-sheriff-resolve') },
    ],
  },
  {
    id: phase('phase-sheriff-runoff-speech'),
    labelKey: 'phases.sheriffRunoffSpeech',
    mode: 'sequential',
    actionType: 'speech',
    actorSelector: 'sheriff-tied-candidates',
    edges: [{ to: phase('phase-sheriff-runoff-vote') }],
  },
  {
    id: phase('phase-sheriff-runoff-vote'),
    labelKey: 'phases.sheriffRunoffVote',
    mode: 'parallel',
    actionType: 'vote',
    actorSelector: 'original-sheriff-noncandidates',
    edges: [{ to: phase('phase-sheriff-resolve') }],
  },
  {
    id: phase('phase-sheriff-resolve'),
    labelKey: 'phases.sheriffResolve',
    mode: 'automatic',
    edges: [{ to: phase('phase-day-announcement') }],
  },
  {
    id: phase('phase-day-announcement'),
    labelKey: 'phases.dayAnnouncement',
    mode: 'automatic',
    edges: [
      { to: phase('phase-death-triggers'), when: 'has-death-trigger' },
      { to: phase('phase-match-ended'), when: 'has-winner' },
      { to: phase('phase-sheriff-transfer'), when: 'dead-sheriff-holds-badge' },
      { to: phase('phase-last-words'), when: 'has-last-words' },
      { to: phase('phase-night-guard'), when: 'interrupted-to-night' },
      { to: phase('phase-day-speech-order') },
    ],
  },
  {
    id: phase('phase-sheriff-transfer'),
    labelKey: 'phases.sheriffTransfer',
    mode: 'parallel',
    actionType: 'skill-trigger',
    abilityId: AbilityIdSchema.parse('ability-sheriff-transfer'),
    actorSelector: 'dead-sheriff',
    edges: [
      { to: phase('phase-death-triggers'), when: 'has-death-trigger' },
      { to: phase('phase-match-ended'), when: 'has-winner' },
      { to: phase('phase-last-words'), when: 'has-last-words' },
      { to: phase('phase-night-guard'), when: 'interrupted-to-night' },
      { to: phase('phase-day-speech-order') },
    ],
  },
  {
    id: phase('phase-death-triggers'),
    labelKey: 'phases.deathTriggers',
    mode: 'sequential',
    actionType: 'skill-trigger',
    actorSelector: 'pending-death-trigger-owners',
    edges: [
      { to: phase('phase-death-triggers'), when: 'has-death-trigger' },
      { to: phase('phase-match-ended'), when: 'has-winner' },
      { to: phase('phase-sheriff-transfer'), when: 'dead-sheriff-holds-badge' },
      { to: phase('phase-last-words'), when: 'has-last-words' },
      { to: phase('phase-night-guard'), when: 'interrupted-to-night' },
      { to: phase('phase-day-speech-order') },
    ],
  },
  {
    id: phase('phase-last-words'),
    labelKey: 'phases.lastWords',
    mode: 'sequential',
    actionType: 'speech',
    actorSelector: 'last-words-eligible',
    edges: [
      { to: phase('phase-match-ended'), when: 'has-winner' },
      { to: phase('phase-night-guard'), when: 'interrupted-to-night' },
      { to: phase('phase-day-speech-order') },
    ],
  },
  {
    id: phase('phase-day-speech-order'),
    labelKey: 'phases.daySpeechOrder',
    mode: 'parallel',
    actionType: 'sheriff-action',
    actorSelector: 'sheriff-or-system',
    edges: [{ to: phase('phase-day-speech') }],
  },
  {
    id: phase('phase-day-speech'),
    labelKey: 'phases.daySpeech',
    mode: 'sequential',
    actionType: 'speech',
    actorSelector: 'day-speech-order',
    edges: [{ to: phase('phase-day-vote') }],
  },
  {
    id: phase('phase-day-vote'),
    labelKey: 'phases.dayVote',
    mode: 'parallel',
    actionType: 'vote',
    actorSelector: 'eligible-voters',
    edges: [
      { to: phase('phase-day-runoff-speech'), when: 'exile-vote-tied' },
      { to: phase('phase-day-resolve') },
    ],
  },
  {
    id: phase('phase-day-runoff-speech'),
    labelKey: 'phases.dayRunoffSpeech',
    mode: 'sequential',
    actionType: 'speech',
    actorSelector: 'exile-tied-players',
    edges: [{ to: phase('phase-day-runoff-vote') }],
  },
  {
    id: phase('phase-day-runoff-vote'),
    labelKey: 'phases.dayRunoffVote',
    mode: 'parallel',
    actionType: 'vote',
    actorSelector: 'eligible-runoff-voters',
    edges: [{ to: phase('phase-day-resolve') }],
  },
  {
    id: phase('phase-day-resolve'),
    labelKey: 'phases.dayResolve',
    mode: 'automatic',
    edges: [
      { to: phase('phase-death-triggers'), when: 'has-death-trigger' },
      { to: phase('phase-match-ended'), when: 'has-winner' },
      { to: phase('phase-sheriff-transfer'), when: 'dead-sheriff-holds-badge' },
      { to: phase('phase-last-words'), when: 'has-last-words' },
      { to: phase('phase-night-guard') },
    ],
  },
  {
    id: phase('phase-match-ended'),
    labelKey: 'phases.matchEnded',
    mode: 'automatic',
    edges: [],
  },
]

export const classicPhaseGraph: PhaseGraph = {
  id: 'classic-sheriff-v1',
  entry: phase('phase-night-guard'),
  nodes: new Map(nodes.map((node) => [node.id, node])),
}
