import { readFile, writeFile } from 'node:fs/promises'
import { readdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join, resolve } from 'node:path'
import { projectRoot } from './files.js'

export const gameCatalogPath = resolve(projectRoot, 'docs/generated/game-catalog.md')

interface PromptManifest {
  readonly roles?: readonly { readonly id: string; readonly label: string }[]
}

interface CopyCatalog {
  readonly roles: Readonly<Record<string, string>>
  readonly boards: Readonly<Record<string, { readonly name: string; readonly description: string }>>
}

export function renderGameCatalog(): string {
  const bundleRoot = resolve(projectRoot, 'packages/assets/prompts/bundles')
  const roles = readdirSync(bundleRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .flatMap((entry) => {
      const manifest = JSON.parse(
        readFileSync(join(bundleRoot, entry.name, 'bundle.json'), 'utf8'),
      ) as PromptManifest
      return manifest.roles ?? []
    })
    .sort((left, right) => left.id.localeCompare(right.id))
  const copy = JSON.parse(
    readFileSync(resolve(projectRoot, 'packages/assets/copy/zh-CN.json'), 'utf8'),
  ) as CopyCatalog
  const boards = Object.values(copy.boards)
  const lines = [
    '<!-- Generated by pnpm docs:generate. Do not edit by hand. -->',
    '',
    '# Game catalog',
    '',
    'This reference is generated from Role-owned Prompt manifests and localized built-in board copy.',
    '',
    '## Roles',
    '',
    ...roles.map((role) => {
      const key = role.id
        .replace(/^role-/, '')
        .replace(/-([a-z])/g, (_match, character: string) => character.toUpperCase())
      return `- \`${role.id}\` — ${copy.roles[key] ?? role.label}`
    }),
    '',
    '## Built-in boards',
    '',
    ...boards.flatMap((board) => [`### ${board.name}`, '', board.description, '']),
    '内置 board 保持只读。自定义 board 可以组合已安装 Roles,使用 6–24 个席位与 0–2 张底牌,',
    '并在每个 Match 中冻结 Ruleset、牌池、政策、Profile defaults 与 Character defaults。',
    '',
  ]
  return lines.join('\n')
}

async function main(): Promise<void> {
  const expected = renderGameCatalog()
  if (process.argv.includes('--check')) {
    const actual = await readFile(gameCatalogPath, 'utf8').catch(() => '')
    if (actual !== expected) {
      console.error('docs/generated/game-catalog.md is stale; run pnpm docs:generate')
      process.exitCode = 1
      return
    }
    process.stdout.write('game catalog is current\n')
    return
  }
  await writeFile(gameCatalogPath, expected)
  process.stdout.write('generated docs/generated/game-catalog.md\n')
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  await main()
}
